export const UI_SET_SCREEN_IS_WIDE = 'UI_SET_SCREEN_IS_WIDE';

export const UI_SET_IS_HOME = 'UI_SET_IS_HOME';

export const UI_SET_ANSWER_FILTER = 'UI_SET_ANSWER_FILTER';

export const UI_SET_QUESTION_INPUT = 'UI_SET_QUESTION_INPUT';

export const UI_TOGGLE_IS_FOUR_OH_FOUR = 'UI_TOGGLE_IS_FOUR_OH_FOUR';

export const UI_SET_NAV_BAR_HEIGHT = 'UI_SET_NAV_BAR_HEIGHT';
