export const ADD_QUESTION = 'ADD_QUESTION';

export const QUESTION_ADD_ANSWER = 'QUESTION_ADD_ANSWER';

export const QUESTIONS_SET_INITIAL = 'QUESTIONS_SET_INITIAL';

export const QUESTION_ADD_QUESTION = 'QUESTION_ADD_QUESTION';
